openapi: 3.1.0
info:
  title: Test Bienestar
  version: 1.0.0
servers:
  - url: https://iaobsdesiaservice.openai.azure.com/openai/deployments/iaobsdesgpt-4o

paths:
  /chat/completions:
    post:
      operationId: askWellbeing
      summary: Pregunta sobre bienestar
      parameters:
        - name: api-version
          in: query
          required: true
          schema:
            type: string
          example: 2025-01-01-preview
      security:
        - apiKeyHeader: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - messages
              properties:
                messages:
                  type: array
                  items:
                    type: object
                    required:
                      - role
                      - content
                    properties:
                      role:
                        type: string
                      content:
                        type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  choices:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: object
                          properties:
                            content:
                              type: string

components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      in: header
      name: api-key

