openapi: 3.1.0
info:
  title: IA Bienestar GPT
  description: API que responde preguntas sobre bienestar usando GPT-4o en Azure y ofrece trazabilidad a fuentes confiables.
  version: 1.0.1
servers:
  - url: https://iaobsdesiaservice.openai.azure.com/openai/deployments/iaobsdesgpt-4o
    description: Endpoint de Azure OpenAI

paths:
  /chat/completions:
    post:
      operationId: askWellbeing
      summary: Haz una pregunta sobre bienestar y recibe una respuesta con trazabilidad a fuentes confiables.
      parameters:
        - name: api-version
          in: query
          required: true
          schema:
            type: string
          example: 2025-01-01-preview
      security:
        - apiKeyHeader: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                messages:
                  type: array
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                        enum: [user]
                      content:
                        type: string
                  example:
                    - role: user
                      content: "¿Qué puedo hacer para dormir mejor?"
                temperature:
                  type: number
                  default: 0.7
                top_p:
                  type: number
                  default: 1.0
      responses:
        '200':
          description: Respuesta del modelo con contenido y trazabilidad
          content:
            application/json:
              schema:
                type: object
                properties:
                  choices:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: object
                          properties:
                            role:
                              type: string
                            content:
                              type: string

components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      in: header
      name: api-key
